spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testeMV
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

